- name: laptop
  include: "{{ distro }}.yml"

- name: required config directories
  become: true
  become_method: sudo
  file: state=directory path={{ item }}
  with_items:
    - "/etc/X11/xorg.conf.d/"

- name: config files
  become: true
  become_method: sudo
  copy: src={{ item.src }} dest={{ item.dest }}
  with_items:
    - {
        src: "{{ role_path }}/files/10-libinput.conf",
        dest: "/etc/X11/xorg.conf.d/10-libinput.conf",
      }

- name: add wireshark group
  become: true
  become_method: sudo
  group:
    name: wireshark
    state: present

- name: add to wireshark group
  become: true
  become_method: sudo
  user:
    name: "{{ ansible_user }}"
    groups: wireshark
    append: "yes"
