- name: gpg keys url
  become: true
  become_method: sudo
  apt_key:
    url: "{{ item }}"
    state: present
  loop:
    - "https://download.spotify.com/debian/pubkey_0D811D58.gpg"
    - "https://updates.signal.org/desktop/apt/keys.asc"

- name: add repos
  become: true
  become_method: sudo
  apt_repository:
    state: present
    repo: "{{ item }}"
    codename: "{{ release }}"
  loop:
    - "ppa:dysfunctionalprogramming/pamixer"
    - "deb http://repository.spotify.com stable non-free"
    - "deb [arch=amd64] https://updates.signal.org/desktop/apt xenial main"

- name: packages
  become: true
  become_method: sudo
  apt:
    install_recommends: no
    name:
      - pamixer
      - openssh-server
      - openvpn
      - hplip
      - tlp
      - fail2ban
      - ffmpeg
      - libreoffice
      - hplip
      - gimp
      - xclip
      - youtube-dl
      - hugo
      - obs-studio
      - rhythmbox
      - peek
      - gphoto2
      - v4l2loopback-dkms
      - audacity
      - pavucontrol
      - spotify-client
      - hexchat
      - signal-desktop
      - fonts-firacode
    state: present

- name: ufw deny all
  become: true
  become_method: sudo
  ufw:
    state: enabled
    policy: deny
    direction: incoming
