- name: gpg keys url
  become: true
  become_method: sudo
  apt_key:
    url: "{{ item }}"
    state: present
  loop:
    - "https://dl.google.com/linux/linux_signing_key.pub"
    - "https://download.spotify.com/debian/pubkey_0D811D58.gpg"

- name: add repos
  become: true
  become_method: sudo
  apt_repository:
    state: present
    repo: "{{ item }}"
    codename: "{{ release }}"
  loop:
    - "ppa:dysfunctionalprogramming/pamixer"
    - "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main"
    - "deb http://repository.spotify.com stable non-free"

- name: packages
  become: true
  become_method: sudo
  apt:
    install_recommends: no
    name:
      - openssh-server
      - openvpn
      - firefox
      - hplip
      - tlp
      - fail2ban
      - ffmpeg
      - gstreamer1.0-plugins-ugly
      - gstreamer1.0-plugins-bad
      - gstreamer1.0-plugins-good
      - pamixer
      - libreoffice
      - hplip
      - gimp
      - inkscape
      - xclip
      - isync
      - mutt
      - newsboat
      - irssi
      - youtube-dl
      - hugo
      - keepassxc
      - obs-studio
      - rhythmbox
      - qt5-style-plugins
      - peek
      - spotify-client
      - google-chrome-stable
      - google-chrome-beta
      - wireshark
      - gphoto2
      - v4l2loopback-dkms
      - brasero
      - rxvt-unicode
      - virtualbox
      - ttf-mscorefonts-installer
      - ubuntu-restricted-extras
      - vlc
      - zim
      - xfonts-unifont
      - transmission-gtk
      - redshift
      - dconf-editor
      - gnome-disk-utility
    state: present

- name: ufw deny all
  become: true
  become_method: sudo
  ufw:
    state: enabled
    policy: deny
    direction: incoming
