- name: gpg keys url
  become: true
  become_method: sudo
  apt_key:
    url: "{{ item }}"
    state: present
  loop:
    - "https://dl.google.com/linux/linux_signing_key.pub"

- name: add repos
  become: true
  become_method: sudo
  apt_repository:
    state: present
    repo: "{{ item }}"
    codename: "{{ release }}"
  loop:
    - "ppa:dysfunctionalprogramming/pamixer"
    - "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main"
    - "deb http://repository.spotify.com stable non-free"

- name: packages
  become: true
  become_method: sudo
  apt:
    install_recommends: no
    name:
      - pamixer
      - openssh-server
      - openvpn
      - hplip
      - tlp
      - fail2ban
      - ffmpeg
      - gstreamer1.0-plugins-ugly
      - gstreamer1.0-plugins-bad
      - gstreamer1.0-plugins-good
      - libreoffice
      - hplip
      - gimp
      - xclip
      - youtube-dl
      - hugo
      - obs-studio
      - rhythmbox
      - peek
      - google-chrome-stable
      - gphoto2
      - v4l2loopback-dkms
      - transmission-gtk
      - weechat
      - audacity
      - pavucontrol
      - celluloid
    state: present

- name: remove packages
  become: true
  become_method: sudo
  apt:
    name:
      - thunderbird
    state: present

- name: disable apport
  become: true
  become_method: sudo
  systemd:
    name: apport
    enabled: false

- name: ufw deny all
  become: true
  become_method: sudo
  ufw:
    state: enabled
    policy: deny
    direction: incoming
