- name: dev packages
  become: true
  become_method: sudo
  apt:
    name:
      - valgrind
      - gdb
      - strace
      - universal-ctags
      - m4
      - jq
      - clang
      - clang-format
      - virtualenv
      - yamllint
    state: present

- name: packages
  become: true
  become_method: sudo
  apt:
    name:
      - openvpn
      - firefox-esr
      - chromium
      - hplip
      - mplayer
      - keepassxc
      - simple-scan
      - gimp
      - xsel
      - mutt
      - newsboat
      - irssi
      - rxvt-unicode
      - youtube-dl
      - redshift
      - transmission-gtk
      - rhythmbox
      - mpv
      - qt5-style-plugins
    state: present
