- name: gpg keys url
  become: true
  become_method: sudo
  apt_key:
    url: "{{ item }}"
    state: present
  loop:
    - "https://adoptopenjdk.jfrog.io/adoptopenjdk/api/gpg/key/public"

- name: add repos
  become: true
  become_method: sudo
  apt_repository:
    state: present
    repo: "{{ item }}"
  loop:
    - "deb https://adoptopenjdk.jfrog.io/adoptopenjdk/deb/ {{ release }} main"

- name: dev packages
  become: true
  become_method: sudo
  apt:
    name:
      - shellcheck
      - valgrind
      - gdb
      - rr
      - strace
      - universal-ctags
      - cscope
      - python-pygments
      - meson
      - ninja-build
      - cmake
      - pandoc
      - reprepro
      - bison
      - flex
      - bc
      - m4
      - texinfo
      - xml-twig-tools
      - jq
      - imagemagick
      - original-awk
      - uuid-runtime
      - dnsutils
      - optipng
      - xvfb
      - bmake
      - freebsd-buildutils
      - mandoc
      - luajit
      - mkosi
      - ksh
      - tcsh
      - zsh
      - mksh
      - clang
      - clang-format
      - clang-tidy
      - intltool
      - redis-tools
      - docker-compose
      - virtualenv
      - pipenv
      - isort
      - flake8
      - black
      - mypy
      - mypy-doc
      - python3-mypy
      - yamllint
      - asciinema
      - meson
      - twine
      - cvs
      - subversion
      - adoptopenjdk-8-hotspot
      - s4cmd
      - devscripts
    state: present

- name: libs
  become: true
  become_method: sudo
  apt:
    name:
      - clang-7
      - lib32z1
      - libasound2
      - libbz2-dev
      - libcairo2-dev
      - libcap-dev
      - libclang-6.0-dev
      - libclang-7-dev
      - libcurl4-openssl-dev
      - libelf-dev
      - libffi-dev
      - libfl-dev
      - libgconf-2-4
      - libgif-dev
      - libgtk2.0-0
      - libgtk-3-dev
      - libinih-dev
      - libllvm6.0
      - libjpeg62-turbo-dev
      - libncurses5-dev
      - libnotify-dev
      - libnss3
      - libpcre3-dev
      - libreadline-dev
      - libseccomp-dev
      - libsqlite3-dev
      - libssl-dev
      - libsystemd-dev
      - libtagc0-dev
      - libxss1
      - llvm-6.0-dev
      - llvm-7-dev
      - llvm-7-runtime
      - systemtap-sdt-dev
      - libavutil-dev
      - libavcodec-dev
      - libavformat-dev
      - libswscale-dev
      - libpulse-dev
      - libinput-dev
      - libgtkmm-3.0-dev
      - libjsoncpp-dev
      - libgit2-dev
      - libevent-dev
      - libxml2-dev
    state: present

- name: packages
  become: true
  become_method: sudo
  apt:
    name:
      - openssh-server
      - openvpn
      - firefox-esr
      - hplip
      - tlp
      - fail2ban
      - ffmpeg
      - qt5-style-plugins
      - gstreamer1.0-plugins-ugly
      - gstreamer1.0-plugins-bad
      - gstreamer1.0-plugins-good
      - discount
      - libreoffice
      - keepassxc
      - simple-scan
      - aria2
      - hplip
      - gimp
      - inkscape
      - xsel
      - vlc
      - isync
      - mutt
      - newsboat
      - irssi
      - silversearcher-ag
      - xterm
      - mpg123
      - chromium
      - youtube-dl
      - redshift
      - dconf-editor
      - transmission-gtk
      - gitg
      - rhythmbox
    state: present
