- name: laptop
  include: "{{ distro }}_{{ release }}.yml"

- name: nvm
  shell: >
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
  args:
    creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"

- name: python 3 packages
  pip:
    name: "{{ item }}"
    executable: pip3
    extra_args: --user
  loop:
    - vim-vint
    - virtualenv
    - poetry
    - yamllint
    - pipenv
    - isort==4.3.12
    - black
