- name: laptop
  include: "{{ distro }}_{{ release }}.yml"

- name: pyenv
  shell: >
    curl -L https://github.com/pyenv/pyenv-installer/raw/master/bin/pyenv-installer | bash
  args:
    creates: "{{ ansible_env.HOME }}/.pyenv"

- name: python 3 packages
  pip:
    name: "{{ item }}"
    executable: pip3
    extra_args: --user
  loop:
    - vim-vint
    - virtualenv
    - yamllint
    - pipenv

- name: required config directories
  become: true
  become_method: sudo
  file: state=directory path={{ item }}
  with_items:
    - "/etc/X11/xorg.conf.d/"

- name: config files
  become: true
  become_method: sudo
  copy: src={{ item.src }} dest={{ item.dest }}
  with_items:
    - {
        src: "{{ role_path }}/files/10-libinput.conf",
        dest: "/etc/X11/xorg.conf.d/10-libinput.conf",
      }
