- name: laptop
  include: "{{ distro }}_{{ release }}.yml"

- name: python packages
  pip:
    name: "{{ item }}"
    executable: pip3
    extra_args: --user
  loop:
    - vim-vint
    - 2to3
    - black
    - isort
    - flake8
    - virtualenv
    - poetry

- name: npm packages
  npm:
    name: "{{ item }}"
    global: true
  with_items:
    - standard
    - csslint
