- name: laptop
  include: "{{ distro }}_{{ release }}.yml"

# - name: python 2.7 pip
# command: "python2.7 get-pip.py"

# - name: python 3.7 pip
# command: "python3.7 get-pip.py"

- name: python 2 packages
  pip:
    name: "{{ item }}"
    executable: pip2
    extra_args: --user
  loop:
    - gsutil

- name: python 3 packages
  pip:
    name: "{{ item }}"
    executable: pip3
    extra_args: --user
  loop:
    - vim-vint
    - virtualenv
    - poetry
    - yamllint
    - pipenv
    - isort==4.3.12
    - black

- name: npm packages
  npm:
    name: "{{ item }}"
    global: true
  with_items:
    - standard
    - csslint
    - prettier
