- name: laptop
  include: "{{ distro }}_{{ release }}.yml"

- name: python 2 packages
  pip:
    name: "{{ item }}"
    executable: pip3
    extra_args: --user
  loop:
    - gsutil

- name: python 3 packages
  pip:
    name: "{{ item }}"
    executable: pip3
    extra_args: --user
  loop:
    - vim-vint
    - virtualenv
    - poetry

- name: npm packages
  npm:
    name: "{{ item }}"
    global: true
  with_items:
    - standard
    - csslint
