- name: add repos
  become: true
  become_method: sudo
  apt_repository:
    state: present
    repo: "{{ item }}"
    codename: "{{ release }}"
  loop:
    - "ppa:dysfunctionalprogramming/pamixer"
    - "ppa:dysfunctionalprogramming/oksh"
    - "ppa:dysfunctionalprogramming/minisign"

- name: dev packages
  become: true
  become_method: sudo
  apt:
    name:
      - shellcheck
      - valgrind
      - gdb
      - rr
      - strace
      - universal-ctags
      - meson
      - ninja-build
      - cmake
      - pandoc
      - reprepro
      - bison
      - flex
      - bc
      - m4
      - texinfo
      - xml-twig-tools
      - jq
      - imagemagick
      - uuid-runtime
      - dnsutils
      - optipng
      - openjdk-8-jdk
      - xvfb
      - bmake
      - luajit
      - mkosi
      # - php
      # - php-curl
      - oksh
      - ksh
      - tcsh
      - zsh
      - mksh
      - clang
      - clang-format
      - clang-tidy
      - minisign
      - golang
      - rustc
      - cargo
      - intltool
      - redis-tools
      - qemu-system
      - qemu-system-x86
      - qemu-system-arm
      - qemu-system-s390x
      - qemu-system-sparc
      - qemu-system-mips
    state: present

- name: libs
  become: true
  become_method: sudo
  apt:
    name:
      - clang-7
      - lib32z1
      - libasound2
      - libbz2-dev
      - libcairo2-dev
      - libcap-dev
      - libclang-6.0-dev
      - libclang-7-dev
      - libcurl4-openssl-dev
      - libelf-dev
      - libffi-dev
      - libfl-dev
      - libgconf-2-4
      - libgif-dev
      - libgtk2.0-0
      - libgtk-3-dev
      - libinih-dev
      - libjpeg9-dev
      - libllvm6.0
      - libncurses5-dev
      - libnotify-dev
      - libnss3
      - libpcre3-dev
      - libreadline-dev
      - libseccomp-dev
      - libsqlite3-dev
      - libssl-dev
      # - libstdc++6:i386
      # - libstdc++6-i386-cross
      - libsystemd-dev
      - libtagc0-dev
      - libxss1
      - llvm-6.0-dev
      - llvm-7-dev
      - llvm-7-runtime
      - systemtap-sdt-dev
      # - zlib1g:i386
      - libavutil-dev
      - libavcodec-dev
      - libavformat-dev
      - libswscale-dev
      - libpulse-dev
      - libinput-dev
      - libgtkmm-3.0-dev
      - libjsoncpp-dev
      - libgit2-dev
      - libevent-dev
    state: present

- name: packages
  become: true
  become_method: sudo
  apt:
    name:
      - openssh-server
      - openvpn
      - firefox
      - hplip
      - tlp
      - fail2ban
      - ffmpeg
      - ubuntu-restricted-extras
      - qt5-style-plugins
      - gstreamer1.0-plugins-ugly
      - gstreamer1.0-plugins-bad
      - gstreamer1.0-plugins-good
      - pamixer
      - discount
      - libreoffice
      - keepassxc
      - rhythmbox
      - simple-scan
      - hplip
      - transmission-gtk
      - gimp
      - xsel
      - vlc
      - isync
      - mutt
      - newsboat
      - irssi
      - silversearcher-ag
      - xterm
      - obs-studio
      - gnome-session
      - gnome-tweaks
      - rtorrent
    state: present

- name: remove packages
  become: true
  become_method: sudo
  apt:
    name:
      - thunderbird
    state: absent
