- name: gpg keys url
  become: true
  become_method: sudo
  apt_key:
    url: "{{ item }}"
    state: present
  loop:
    - "https://dl.google.com/linux/linux_signing_key.pub"
    - "https://download.spotify.com/debian/pubkey.gpg"

- name: add repos
  become: true
  become_method: sudo
  apt_repository:
    state: present
    repo: "{{ item }}"
    codename: "{{ release }}"
  loop:
    #- "ppa:dysfunctionalprogramming/pamixer"
    #- "ppa:dysfunctionalprogramming/oksh"
    #- "ppa:dysfunctionalprogramming/minisign"
    - "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main"
    - "deb http://repository.spotify.com stable non-free"

- name: dev packages
  become: true
  become_method: sudo
  apt:
    name:
      - shellcheck
      - valgrind
      - gdb
      - strace
      - universal-ctags
      - cscope
      - ninja-build
      - cmake
      - bison
      - flex
      - bc
      - m4
      - xml-twig-tools
      - jq
      - imagemagick
      - uuid-runtime
      - dnsutils
      - openjdk-8-jdk
      #- oksh
      - clang
      - clang-format
      - clang-tidy
      #- minisign
      - virtualenv
      - pipenv
      - s3cmd
      - flake8
      - mypy
      - mypy-doc
      - python3-mypy
      - yamllint
      - asciinema
      - meson
      - golang
    state: present

- name: packages
  become: true
  become_method: sudo
  apt:
    name:
      - openssh-server
      - openvpn
      - firefox
      - hplip
      - tlp
      - fail2ban
      - ffmpeg
      - ubuntu-restricted-extras
      - qt5-style-plugins
      - gstreamer1.0-plugins-ugly
      - gstreamer1.0-plugins-bad
      - gstreamer1.0-plugins-good
      #- pamixer
      - libreoffice
      - simple-scan
      - transmission-gtk
      - hplip
      - gimp
      - inkscape
      - xsel
      - xclip
      - vlc
      - isync
      - mutt
      - newsboat
      - irssi
      - silversearcher-ag
      - google-chrome-stable
      - youtube-dl
      - hugo
      - spotify-client
      - keepassxc
      - obs-studio
      - peek
      - rxvt-unicode
    state: present

- name: disable apport
  become: true
  become_method: sudo
  systemd:
    name: apport
    enabled: false
