- name: gpg keys url
  become: true
  become_method: sudo
  apt_key:
    url: "{{ item }}"
    state: present
  loop:
    - "https://dl.google.com/linux/linux_signing_key.pub"
    - "https://download.spotify.com/debian/pubkey.gpg"

- name: add repos
  become: true
  become_method: sudo
  apt_repository:
    state: present
    repo: "{{ item }}"
    codename: "{{ release }}"
  loop:
    - "ppa:dysfunctionalprogramming/pamixer"
    - "ppa:dysfunctionalprogramming/oksh"
    - "ppa:dysfunctionalprogramming/minisign"
    - "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main"
    - "deb http://repository.spotify.com stable non-free"

- name: remove packages
  become: true
  become_method: sudo
  apt:
    name:
      - thunderbird
      - cheese
      - deja-dup
      - deja-dup-caja
      - shotwell
      - orca
      - onboard
      - magnus
      - evolution
      - hexchat
    state: absent

- name: dev packages
  become: true
  become_method: sudo
  apt:
    name:
      # - shellcheck (defer to docker image instead)
      - valgrind
      - gdb
      - rr
      - strace
      - universal-ctags
      - cscope
      - python-pygments
      - meson
      - ninja-build
      - cmake
      - pandoc
      - reprepro
      - bison
      - flex
      - bc
      - m4
      - texinfo
      - xml-twig-tools
      - jq
      - imagemagick
      - original-awk
      - uuid-runtime
      - dnsutils
      - optipng
      - openjdk-8-jdk
      - xvfb
      - bmake
      - freebsd-buildutils
      - mandoc
      - luajit
      - mkosi
      # - php
      # - php-curl
      - oksh
      - rc
      - ksh
      - tcsh
      - zsh
      - mksh
      - fish
      - clang
      - clang-format
      - clang-tidy
      - minisign
      - intltool
      - redis-tools
      - virtualbox
      - virtualbox-qt
      - docker-compose
      - virtualenv
      - pipenv
      - s3cmd
      - flake8
      - mypy
      - mypy-doc
      - python3-mypy
      - yamllint
      - asciinema
      - meson
      - twine
      - cvs
      - subversion
      - git-extras
      - golang
    state: present

- name: libs
  become: true
  become_method: sudo
  apt:
    name:
      - clang-7
      - lib32z1
      - libasound2
      - libbz2-dev
      - libcairo2-dev
      - libcap-dev
      - libclang-6.0-dev
      - libclang-7-dev
      - libcurl4-openssl-dev
      - libelf-dev
      - libffi-dev
      - libfl-dev
      - libgconf-2-4
      - libgif-dev
      - libgtk2.0-0
      - libgtk-3-dev
      - libinih-dev
      - libjpeg9-dev
      - libllvm6.0
      - libncurses5-dev
      - libnotify-dev
      - libnss3
      - libpcre3-dev
      - libreadline-dev
      - libseccomp-dev
      - libsqlite3-dev
      - libssl-dev
      # - libstdc++6:i386
      # - libstdc++6-i386-cross
      - libsystemd-dev
      - libtagc0-dev
      - libxss1
      - llvm-6.0-dev
      - llvm-7-dev
      - llvm-7-runtime
      - systemtap-sdt-dev
      # - zlib1g:i386
      - libavutil-dev
      - libavcodec-dev
      - libavformat-dev
      - libswscale-dev
      - libpulse-dev
      - libinput-dev
      - libgtkmm-3.0-dev
      - libjsoncpp-dev
      - libgit2-dev
      - libevent-dev
      - libxml2-dev
    state: present

- name: packages
  become: true
  become_method: sudo
  apt:
    name:
      - openssh-server
      - openvpn
      - firefox
      - hplip
      - tlp
      - fail2ban
      - ffmpeg
      - ubuntu-restricted-extras
      - qt5-style-plugins
      - gstreamer1.0-plugins-ugly
      - gstreamer1.0-plugins-bad
      - gstreamer1.0-plugins-good
      - pamixer
      - discount
      - libreoffice
      - simple-scan
      - transmission-gtk
      - hplip
      - gimp
      - inkscape
      - xsel
      - vlc
      - isync
      - mutt
      - newsboat
      - irssi
      - silversearcher-ag
      - xterm
      - google-chrome-stable
      - youtube-dl
      - redshift
      - hugo
      - spotify-client
      - mysql-workbench
    state: present

- name: disable apport
  become: true
  become_method: sudo
  systemd:
    name: apport
    enabled: false
