- name: gpg keys url
  become: true
  become_method: sudo
  apt_key:
    url: "{{ item }}"
    state: present
  loop:
    - "https://dl.google.com/linux/linux_signing_key.pub"
    - "https://dysfunctionalprogramming.com/public/keys/0x23A72C050145EFA8.pub"

- name: add repos
  become: true
  become_method: sudo
  apt_repository:
    state: present
    repo: "{{ item }}"
    codename: "{{ release }}"
  loop:
    #- "ppa:dysfunctionalprogramming/pamixer"
    - "ppa:dysfunctionalprogramming/oksh"
    #- "ppa:dysfunctionalprogramming/minisign"
    - "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main"
    - "deb [arch=amd64] https://dysfunctionalprogramming.com/deb/ focal main"

- name: dev packages
  become: true
  become_method: sudo
  apt:
    name:
      - shellcheck
      - valgrind
      - gdb
      - strace
      - universal-ctags
      - m4
      - jq
      - uuid-runtime
      - dnsutils
      - openjdk-8-jdk
      - oksh
      - clang
      - clang-format
      - clang-tidy
      #- minisign
      - s3cmd
      - libreadline-dev
      - libbz2-dev
      - libsqlite3-dev
      - golang
      - devscripts
      - debhelper
      - reprepro
      - meson
      - tidy
      - rf
      - perltidy
    state: present

- name: packages
  become: true
  become_method: sudo
  apt:
    name:
      - openssh-server
      - openvpn
      - firefox
      - hplip
      - tlp
      - fail2ban
      - ffmpeg
      - gstreamer1.0-plugins-ugly
      - gstreamer1.0-plugins-bad
      - gstreamer1.0-plugins-good
      #- pamixer
      - libreoffice
      - hplip
      - gimp
      - inkscape
      - xclip
      - isync
      - newsboat
      - irssi
      - mutt
      - google-chrome-stable
      - google-chrome-beta
      - youtube-dl
      - hugo
      - keepassxc
      - obs-studio
      - kdenlive
      - rxvt-unicode
      - rhythmbox
    state: present

- name: disable apport
  become: true
  become_method: sudo
  systemd:
    name: apport
    enabled: false

- name: ufw deny all
  become: true
  become_method: sudo
  ufw:
    state: enabled
    policy: deny
    direction: incoming
