- name: dev packages
  become: true
  become_method: sudo
  apt:
    name:
      - shellcheck
      - valgrind
      - gdb
      - strace
      - universal-ctags
      - m4
      - jq
      - uuid-runtime
      - dnsutils
      - clang
      - clang-format
      - s3cmd
      - libreadline-dev
      - libbz2-dev
      - libsqlite3-dev
      - golang
      - devscripts
      - debhelper
    state: present
