- name: add repos
  become: true
  become_method: sudo
  apt_repository:
    state: present
    repo: "{{ item }}"
    codename: "{{ release }}"
  loop:
    - "ppa:dysfunctionalprogramming/oksh"
    - "ppa:dysfunctionalprogramming/minisign"

- name: dev packages
  become: true
  become_method: sudo
  apt:
    name:
      - shellcheck
      - valgrind
      - gdb
      - lldb
      - m4
      - clang
      - clang-format
      - clang-tidy
      - clangd
      - bear
      - minisign
      - devscripts
      - debhelper
      - reprepro
      - meson
      - certbot
      - cmake
      - flex
      - bison
      - uchardet
      - oksh
      - xvfb
      - scdoc
      - hugo
      - zzuf
      - afl++
      - tesseract-ocr
      - pkg-config
      - automake
      - libtool
      - libssl-dev
      - libreadline-dev
      - libbz2-dev
      - libsqlite3-dev
      - libjpeg-dev
      - libcurl4-openssl-dev
      - libelf-dev
      - libgdk-pixbuf2.0-0
      - libgit2-dev
      - libgtk-3-0
      - liblzma-dev
      - libnss3
      - libreadline-dev
      - libx11-dev
      - libxcursor1
      - libxss1
      - golang
      - tesseract-ocr
      - tcc
    state: present
